export const ObjectTypes = {
	2: "Group",
	3: "Shape"
}

export const ObjectProperties = {
	0: "shapeModifier0",
	1: "shapeModifier1",

	8: "height",
	9: "width",

	12: "paths",

	14: "fillEnabled",
	15: "fillColor",
	16: "fillOpacity",

	18: "borderPattern",
	19: "borderColor",
	22: "borderThickness",

	61: "fillGradientColors",

	126: "reflectionEnabled",

	135: "borderStyle"
}

export const ShapeTypes = {
	1: "Customised",
	2: "Word art",
	3: "Image",
	4: "Scribble",
	5: "Line",
	6: "Rectangle",
	7: "Rounded Rectangle",
	8: "Oval",
	9: "Arc",
	10: "Bent Arrow",
	11: "Bent-Up Arrow",
	12: "Bevel",
	13: "Block Arc",
	14: "Double Brace",
	15: "Double Bracket",
	16: "Can",
	17: "Chevron",
	18: "Chord",
	19: "Cloud",
	20: "L-Shape",
	21: "Cube",
	22: "Curved Down Arrow",
	23: "Curved Left Arrow",
	24: "Curved Right Arrow",
	25: "Curved Up Arrow",
	26: "Decagon",
	27: "Diagonal Stripe",
	28: "Diamond",
	29: "Dodecagon",
	30: "Donut",
	31: "Double Wave",
	32: "Down Arrow",
	33: "Down Arrow Callout",
	34: "Folded Corner",
	35: "Frame",
	36: "Half Frame",
	37: "Heart",
	38: "Heptagon",
	39: "Hexagon",
	40: "Pentagon",
	41: "Horizontal Scroll",
	42: "Explosion 1",
	43: "Explosion 2",
	44: "Left Arrow",
	45: "Left Arrow Callout",
	46: "Left Brace",
	47: "Left Bracket",
	48: "Left-Right Arrow",
	49: "Left-Right Arrow Callout",
	50: "Left-Right-Up Arrow",
	51: "Left-Up Arrow",
	52: "Lightning Bolt",
	53: "Divide",
	54: "Equal",
	55: "Minus",
	56: "Multiply",
	57: "Not Equal",
	58: "Plus",
	59: "Moon",
	60: "\"No\" Symbol",
	61: "Notched Right Arrow",
	62: "Octagon",
	63: "Parallelogram",
	64: "Regular Pentagon",
	65: "Pie",
	66: "Plaque",
	67: "Cross",
	68: "Quad Arrow",
	69: "Quad Arrow Callout",
	70: "Down Ribbon",
	71: "Up Ribbon",
	72: "Right Arrow",
	73: "Right Arrow Callout",
	74: "Right Brace",
	75: "Right Bracket",
	76: "Round Single Corner Rectangle",
	77: "Round Diagonal Corner Rectangle",
	78: "Round Same Side Corner Rectangle",
	79: "Right Triangle",
	80: "Smiley Face",
	81: "Snip Single Corner Rectangle",
	82: "Snip Diagonal Corner Rectangle",
	83: "Snip Same Side Corner Rectangle",
	84: "Snip and Round Single Corner Rectangle",
	85: "10-Point Star",
	86: "12-Point Star",
	87: "16-Point Star",
	88: "24-Point Star",
	89: "32-Point Star",
	90: "4-Point Star",
	91: "5-Point Star",
	92: "6-Point Star",
	93: "7-Point Star",
	94: "8-Point Star",
	95: "Striped Right Arrow",
	96: "Sun",
	97: "Trapezoid",
	98: "Triangle",
	99: "Up Arrow",
	100: "Up Arrow Callout",
	101: "Up-Down Arrow",
	102: "U-Turn Arrow",
	103: "Vertical Scroll",
	104: "Wave",
	105: "Oval Callout",
	106: "Rectangular Callout",
	107: "Rounded Rectangular Callout",
	108: "Text Box",
	109: "Flow Chart: Alternate Process",
	110: "Flow Chart: Collate",
	111: "Flow Chart: Connector",
	112: "Flow Chart: Decision",
	113: "Flow Chart: Delay",
	114: "Flow Chart: Display",
	115: "Flow Chart: Document",
	116: "Flow Chart: Extract",
	117: "Flow Chart: Data",
	118: "Flow Chart: Internal Storage",
	119: "Flow Chart: Magnetic Disk",
	120: "Flow Chart: Direct Access Storage",
	121: "Flow Chart: Sequential Access Storage",
	122: "Flow Chart: Manual Input",
	123: "Flow Chart: Manual Operation",
	124: "Flow Chart: Merge",
	125: "Flow Chart: Multi-document",
	126: "Flow Chart: Offline Storage",
	127: "Flow Chart: Off-page Connector",
	128: "Flow Chart: Stored Data",
	129: "Flow Chart: Or",
	130: "Flow Chart: Predefined Process",
	131: "Flow Chart: Preparation",
	132: "Flow Chart: Process",
	133: "Flow Chart: Card",
	134: "Flow Chart: Punched Tape",
	135: "Flow Chart: Sort",
	136: "Flow Chart: Summing Junction",
	137: "Flow Chart: Terminator",
	138: "Polyline",
	139: "Polygon",
	140: "Right Arrow",
	141: "Diagonal Arrow",
	142: "Up Arrow",
	143: "Oval Callout",
	144: "24-Point Star",
	145: "Elbow connector",
	146: "Elbow connector",
	147: "Elbow connector",
	148: "Elbow connector",
	149: "Curved connector",
	150: "Curved connector",
	151: "Curved connector",
	152: "Curved connector",
	153: "Line",
	154: "Curve",
	155: "Table",
	157: "Video",
	159: "Teardrop",
	160: "Curved Down Ribbon",
	161: "Curved Up Ribbon",
	162: "Cloud Callout",
	164: "Ink stroke",
}

export const LineEndings = {
	0: "None",
	1: "Filled square",
	2: "Hollow square",
	3: "Filled circle",
	4: "Hollow circle",
	5: "Filled arrow",
	6: "Hollow arrow",
	7: "Notched arrow",
	8: "Filled diamond",
	9: "Hollow diamond"
}

export const LineStyles = {
	0: "Single",
	1: "Double",
	2: "Triple",
	3: "Thick-thin",
	4: "Thin-thick"
}

export const LinePatterns = {
	0: "Solid",
	1: "Dot",
	2: "Dash",
	3: "Dash dot",
	4: "Long dash",
	5: "Long dash dot"
}