export const LineEndings = {
    0: "None",
    1: "Filled square",
    2: "Hollow square",
    3: "Filled circle",
    4: "Hollow circle",
    5: "Filled arrow",
    6: "Hollow arrow",
    7: "Notched arrow",
    8: "Filled diamond",
    9: "Hollow diamond"
}

export const LineStyles = {
    0: "Single",
    1: "Double",
    2: "Triple",
    3: "Thick-thin",
    4: "Thin-thick"
}

export const LinePatterns = {
    0: "Solid",
    1: "Dot",
    2: "Dash",
    3: "Dash dot",
    4: "Long dash",
    5: "Long dash dot"
}

export const ShapeTypes = {
    1: "Customised",
    6: "Rectangle",
    7: "Rounded Rectangle",
    81: "Snip Single Corner Rectangle",
    83: "Snip Same Side Corner Rectangle",
    82: "Snip Diagonal Corner Rectangle",
    84: "Snip and Round Single Corner Rectangle",
    76: "Round Single Corner Rectangle",
    78: "Round Same Side Corner Rectangle",
    77: "Round Diagonal Corner Rectangle",
    2: "Word art",
    8: "Oval",
    98: "Triangle",
    79: "Right Triangle",
    63: "Parallelogram",
    97: "Trapezoid",
    28: "Diamond",
    64: "Regular Pentagon",
    39: "Hexagon",
    38: "Heptagon",
    62: "Octagon",
    26: "Decagon",
    29: "Dodecagon",
    65: "Pie",
    18: "Chord",
    35: "Frame",
    36: "Half Frame",
    20: "L-Shape",
    27: "Diagonal Stripe",
    67: "Cross",
    66: "Plaque",
    16: "Can",
    21: "Cube",
    12: "Bevel",
    30: "Donut",
    60: '"No" Symbol',
    13: "Block Arc",
    34: "Folded Corner",
    80: "Smiley Face",
    37: "Heart",
    52: "Lightning Bolt",
    96: "Sun",
    59: "Moon",
    19: "Cloud",
    9: "Arc",
    15: "Double Bracket",
    14: "Double Brace",
    47: "Left Bracket",
    75: "Right Bracket",
    46: "Left Brace",
    74: "Right Brace",
    72: "Right Arrow",
    44: "Left Arrow",
    99: "Up Arrow",
    140: "Right Arrow",
    142: "Up Arrow",
    141: "Diagonal Arrow",
    32: "Down Arrow",
    48: "Left-Right Arrow",
    101: "Up-Down Arrow",
    68: "Quad Arrow",
    50: "Left-Right-Up Arrow",
    10: "Bent Arrow",
    102: "U-Turn Arrow",
    51: "Left-Up Arrow",
    11: "Bent-Up Arrow",
    24: "Curved Right Arrow",
    23: "Curved Left Arrow",
    25: "Curved Up Arrow",
    22: "Curved Down Arrow",
    95: "Striped Right Arrow",
    61: "Notched Right Arrow",
    40: "Pentagon",
    17: "Chevron",
    73: "Right Arrow Callout",
    33: "Down Arrow Callout",
    45: "Left Arrow Callout",
    100: "Up Arrow Callout",
    49: "Left-Right Arrow Callout",
    69: "Quad Arrow Callout",
    58: "Plus",
    55: "Minus",
    56: "Multiply",
    53: "Divide",
    54: "Equal",
    57: "Not Equal",
    132: "Flow Chart: Process",
    109: "Flowchart: Alternate Process",
    112: "Flow Chart: Decision",
    117: "Flowchart: Data",
    130: "Flow Chart: Predefined Process",
    118: "Flow Chart: Internal Storage",
    115: "Flowchart: Document",
    125: "Flow Chart: Multi-document",
    137: "Flow Chart: Terminator",
    131: "Flow Chart: Preparation",
    122: "Flowchart: Manual Input",
    123: "Flow Chart: Manual Operation",
    111: "Flow Chart: Connector",
    126: "Flow Chart: Offline Storage",
    127: "Flowchart: Off-page Connector",
    133: "Flow Chart: Card",
    134: "Flowchart: Punched Tape",
    136: "Flow Chart: Summing Junction",
    129: "Flowchart: Or",
    110: "Flowchart: Collate",
    135: "Flowchart: Sort",
    116: "Flow Chart: Extract",
    124: "Flow Chart: Merge",
    128: "Flowchart: Stored Data",
    113: "Flow Chart: Delay",
    121: "Flow Chart: Sequential Access Storage",
    119: "Flow Chart: Magnetic Disk",
    120: "Flowchart: Direct Access Storage",
    114: "Flowchart: Display",
    42: "Explosion 1",
    43: "Explosion 2",
    90: "4-Point Star",
    91: "5-Point Star",
    92: "6-Point Star",
    93: "7-Point Star",
    94: "8-Point Star",
    85: "10-Point Star",
    86: "12-Point Star",
    87: "16-Point Star",
    88: "24-Point Star",
    144: "24-Point Star",
    89: "32-Point Star",
    71: "Up Ribbon",
    70: "Down Ribbon",
    103: "Vertical Scroll",
    41: "Horizontal Scroll",
    104: "Wave",
    31: "Double Wave",
    106: "Rectangular Callout",
    107: "Rounded Rectangular Callout",
    105: "Oval Callout",
    143: "Oval Callout",
    159: "Teardrop",
    161: "Curved Up Ribbon",
    160: "Curved Down Ribbon",
    162: "Cloud Callout",
    108: "Text Box",
    5: "Line",
    153: "Line",
    145: "Elbow connector",
    146: "Elbow connector",
    147: "Elbow connector",
    148: "Elbow connector",
    149: "Curved connector",
    150: "Curved connector",
    151: "Curved connector",
    152: "Curved connector",
    139: "Polygon",
    138: "Polyline",
    154: "Curve",
    4: "Scribble",
    3: "Image",
    157: "Video",
    164: "Ink stroke",
    155: "Table"
}


// Object properties
export const ObjectProperties = {
    0: "shapeModifier0",
    1: "shapeModifier1",
    12: "paths",
    15: "fillColor",
    16: "fillOpacity",
    19: "borderColor",
    22: "borderThickness",
    61: "fillGradientColors",
    126: "reflectionEnabled",
}